#!/bin/bash
# Move apps to spaces via Yabai with friendly app names

wid=$(yabai -m query --windows | jq ".[] | select(.app == \"$1\") | .id")

if [ -z "$wid" ]; then
    echo "No window found for $1"
    exit 1
fi

yabai -m window $wid --space $2
